# Generated by Django 5.1.2 on 2024-10-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackedcurrency',
            old_name='Currency',
            new_name='currency',
        ),
    ]
