# Generated by Django 5.1.2 on 2024-10-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0002_rename_currency_trackedcurrency_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedcurrency',
            name='currency',
            field=models.IntegerField(max_length=64),
        ),
    ]
