# Generated by Django 5.1.2 on 2024-10-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0003_alter_trackedcurrency_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedcurrency',
            name='currency',
            field=models.IntegerField(),
        ),
    ]
