# Generated by Django 5.1.2 on 2024-10-25 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
    ]
