# Generated by Django 5.1.2 on 2024-10-25 16:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_unverifieduser_remove_customuser_activation_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unverifieduser',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
