# Generated by Django 5.1.2 on 2024-10-26 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_unverifieduser_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='unverifieduser',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
