# Generated by Django 5.1.2 on 2024-10-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_unverifieduser_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unverifieduser',
            name='created',
        ),
        migrations.AddField(
            model_name='unverifieduser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
