# Generated by Django 5.1.2 on 2024-10-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_unverifieduser_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unverifieduser',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='unverifieduser',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
