# Generated by Django 5.1.2 on 2024-10-26 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_unverifieduser_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unverifieduser',
            name='created_at',
        ),
    ]
