# Generated by Django 5.1.2 on 2024-10-31 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_daily_updates_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='daily_updates_enabled',
        ),
    ]
